# Site settings
title: Pavo Studio
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pavo Studio
user_description: From A Distance Of 180 Light Years
user_title: 
email: pavostudio@hotmail.com
github_username:  pavostudio

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
